import { motion, AnimatePresence } from 'motion/react';
import { X, ExternalLink, Clipboard, Check } from 'lucide-react';
import { useState } from 'react';

interface WebsiteViewerProps {
  url: string;
  onClose: () => void;
}

export function WebsiteViewer({ url, onClose }: WebsiteViewerProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95, y: 20 }}
      animate={{ opacity: 1, scale: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.95, y: 20 }}
      className="fixed inset-0 z-[100] bg-beatrice-bg flex flex-col"
    >
      {/* Header */}
      <header className="px-6 py-4 border-b border-white/10 flex items-center justify-between bg-beatrice-surface/85 backdrop-blur-xl">
        <div className="flex flex-col">
          <h2 className="text-beatrice-text text-sm font-bold tracking-widest uppercase">Web Architect</h2>
          <p className="text-beatrice-teal/70 text-[10px] font-mono truncate max-w-[200px] sm:max-w-md">{url}</p>
        </div>
        
        <div className="flex items-center gap-3">
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/5 hover:bg-white/10 text-white/70 hover:text-white transition-all text-xs"
          >
            {copied ? <Check size={14} className="text-beatrice-live" /> : <Clipboard size={14} />}
            {copied ? 'Copied' : 'Copy Link'}
          </button>
          
          <button
            onClick={() => window.open(url, '_blank')}
            className="p-2 rounded-full bg-white/5 hover:bg-white/10 text-white/70 hover:text-white transition-all"
          >
            <ExternalLink size={18} />
          </button>
          
          <button
            onClick={onClose}
            className="p-2 rounded-full bg-white/5 hover:bg-white/10 text-white/70 hover:text-white transition-all"
          >
            <X size={18} />
          </button>
        </div>
      </header>

      {/* Mobile Preview Frame */}
      <div className="flex-1 bg-beatrice-bg p-4 sm:p-8 flex justify-center overflow-hidden">
        <div className="relative w-full max-w-[375px] h-full bg-white rounded-[40px] border-[8px] border-beatrice-surface shadow-2xl shadow-beatrice-deep overflow-hidden flex flex-col">
          {/* Notch Area */}
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-40 h-7 bg-beatrice-surface rounded-b-2xl z-20 flex items-center justify-center">
            <div className="w-12 h-1 bg-white/10 rounded-full" />
          </div>
          
          {/* Iframe */}
          <iframe 
            src={url} 
            className="w-full h-full border-none pt-2"
            title="Website Preview"
          />
          
          {/* Home Indicator */}
          <div className="absolute bottom-1 left-1/2 -translate-x-1/2 w-32 h-1.5 bg-black/20 rounded-full z-20" />
        </div>
      </div>
      
      {/* Footer Info */}
      <footer className="px-8 py-6 bg-beatrice-surface border-t border-white/5 text-center">
        <p className="text-beatrice-secondary/55 text-[10px] tracking-wide uppercase">
          Architecture generated by Beatrice • Deployed to Eburon Cloud
        </p>
      </footer>
    </motion.div>
  );
}
